# Use the official .NET SDK image to build the app.
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

# Copy the .csproj file and restore any dependencies.
COPY . ./

RUN dotnet restore

# Build the application.
RUN dotnet publish -c Release -o out

# Use the official .NET runtime image for the final image.
FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
COPY --from=build-env /app/out .

# Expose port 8080 for HTTP.
EXPOSE 8080

# Define the entry point for the container.
ENTRYPOINT ["dotnet", "LetsDuckingGame.dll"]
